version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:15
    container_name: fastapi-ca-postgres
    environment:
      POSTGRES_DB: fastapi_ca
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d fastapi_ca"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: